FROM wiiuenv/devkitppc:20230218

WORKDIR tmp_build
COPY . .
RUN make clean && make && mkdir -p /artifacts/wups && cp -r lib /artifacts/wups && cp -r include /artifacts/wups && cp -r share /artifacts/wups
WORKDIR /artifacts

FROM scratch as libwups
COPY --from=0 /artifacts /artifacts

FROM wiiuenv/devkitppc:20230218

COPY --from=libwups /artifacts $DEVKITPRO

WORKDIR project
